CONFIG_ZMK_SLEEP=y

CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=1
